import "styles/styles.css";
import type { Metadata } from 'next'
import { ibmPlexMono, libreFranklin } from 'app/_theme/fonts'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${libreFranklin.variable} ${ibmPlexMono.variable}`}>
      <body >{children}</body>
    </html>
  )
}
